### ISSUE TITLE
Mizu fails to compile on Debian 11.3 ARM via Parallels

### ISSUE THREAD

**Issue by Shock9616** [kentjhall/mizu#4]
While following the instructions in the README to install onto my Debian VM, the `make -j$(nproc)` command fails with this fatal error:
```
In file included from ./core/loader/loader.h:18,
                 from core/hle/service/service.h:28,
                 from mizu.cpp:7:
./core/hle/kernel/code_set.h:11:10: fatal error: linux/horizon.h: No such file or directory
   11 | #include <linux/horizon.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: mizu.o] Error 1
make: *** Waiting for unfinished jobs....
rm video_core/bootmanager.moc.cpp
```
There are quite a few warnings being spit out in the output as well.

My computer is a 14" M1 Pro MacBook Pro, the VM is running with Parallels Desktop 18.1.0, and it's the default Debian 11.3 ARM installation that Parallels gives you. I haven't made any modifications to it aside from installing the dependancies for this project.

Here is the full output of the `make -j$(nproc)` command: [output.txt](https://github.com/kentjhall/mizu/files/10048945/output.txt)
